// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.object("CommentaryLog", {
  id: __t.string(),
  matchId: __t.string(),
  tsMs: __t.i64(),
  tone: __t.string(),
  lang: __t.string(),
  text: __t.string(),
  metaJson: __t.string(),
});


