// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.9.0 (commit e26e7fee502eb84c9d677def7052508c6d219cd6).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  convertToAccessorMap as __convertToAccessorMap,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";

// Import and reexport all reducer arg types
import BuyNow from "./buy_now_reducer";
export { BuyNow };
import CloseListingAndTransfer from "./close_listing_and_transfer_reducer";
export { CloseListingAndTransfer };
import CreateAuction from "./create_auction_reducer";
export { CreateAuction };
import CreateListing from "./create_listing_reducer";
export { CreateListing };
import FinalizeAuction from "./finalize_auction_reducer";
export { FinalizeAuction };
import GrantStarterPack from "./grant_starter_pack_reducer";
export { GrantStarterPack };
import InboxMarkRead from "./inbox_mark_read_reducer";
export { InboxMarkRead };
import LinkWallet from "./link_wallet_reducer";
export { LinkWallet };
import PlaceBid from "./place_bid_reducer";
export { PlaceBid };

// Import and reexport all table handle types
import AuctionRow from "./auction_table";
export { AuctionRow };
import BidRow from "./bid_table";
export { BidRow };
import EventRow from "./event_table";
export { EventRow };
import IdempotencyRow from "./idempotency_table";
export { IdempotencyRow };
import InboxRow from "./inbox_table";
export { InboxRow };
import InventoryItemRow from "./inventory_item_table";
export { InventoryItemRow };
import ListingRow from "./listing_table";
export { ListingRow };
import StarterClaimRow from "./starter_claim_table";
export { StarterClaimRow };
import UserRow from "./user_table";
export { UserRow };
import WalletLinkRow from "./wallet_link_table";
export { WalletLinkRow };

// Import and reexport all types
import Auction from "./auction_type";
export { Auction };
import Bid from "./bid_type";
export { Bid };
import Event from "./event_type";
export { Event };
import Idempotency from "./idempotency_type";
export { Idempotency };
import Inbox from "./inbox_type";
export { Inbox };
import InventoryItem from "./inventory_item_type";
export { InventoryItem };
import Listing from "./listing_type";
export { Listing };
import StarterClaim from "./starter_claim_type";
export { StarterClaim };
import User from "./user_type";
export { User };
import WalletLink from "./wallet_link_type";
export { WalletLink };


const tablesSchema = __schema(
  __table({
    name: 'auction',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'auction_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, AuctionRow),
  __table({
    name: 'bid',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'bid_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, BidRow),
  __table({
    name: 'event',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'event_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, EventRow),
  __table({
    name: 'idempotency',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'idempotency_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, IdempotencyRow),
  __table({
    name: 'inbox',
    indexes: [
      { name: 'msg_id', algorithm: 'btree', columns: [
        'msgId',
      ] },
    ],
    constraints: [
      { name: 'inbox_msg_id_key', constraint: 'unique', columns: ['msg_id'] },
    ],
  }, InboxRow),
  __table({
    name: 'inventory_item',
    indexes: [
      { name: 'item_id', algorithm: 'btree', columns: [
        'itemId',
      ] },
    ],
    constraints: [
      { name: 'inventory_item_item_id_key', constraint: 'unique', columns: ['item_id'] },
    ],
  }, InventoryItemRow),
  __table({
    name: 'listing',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'listing_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ListingRow),
  __table({
    name: 'starter_claim',
    indexes: [
      { name: 'fid', algorithm: 'btree', columns: [
        'fid',
      ] },
    ],
    constraints: [
      { name: 'starter_claim_fid_key', constraint: 'unique', columns: ['fid'] },
    ],
  }, StarterClaimRow),
  __table({
    name: 'user',
    indexes: [
      { name: 'fid', algorithm: 'btree', columns: [
        'fid',
      ] },
    ],
    constraints: [
      { name: 'user_fid_key', constraint: 'unique', columns: ['fid'] },
    ],
  }, UserRow),
  __table({
    name: 'wallet_link',
    indexes: [
      { name: 'address', algorithm: 'btree', columns: [
        'address',
      ] },
    ],
    constraints: [
      { name: 'wallet_link_address_key', constraint: 'unique', columns: ['address'] },
    ],
  }, WalletLinkRow),
);

const reducersSchema = __reducers(
  __reducerSchema("BuyNow", BuyNow),
  __reducerSchema("CloseListingAndTransfer", CloseListingAndTransfer),
  __reducerSchema("CreateAuction", CreateAuction),
  __reducerSchema("CreateListing", CreateListing),
  __reducerSchema("FinalizeAuction", FinalizeAuction),
  __reducerSchema("GrantStarterPack", GrantStarterPack),
  __reducerSchema("InboxMarkRead", InboxMarkRead),
  __reducerSchema("LinkWallet", LinkWallet),
  __reducerSchema("PlaceBid", PlaceBid),
);

const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "1.9.0" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType
>;

export const tables = __convertToAccessorMap(tablesSchema.schemaType.tables);
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);


export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;

export class SubscriptionBuilder extends __SubscriptionBuilderImpl<
  typeof REMOTE_MODULE
> {}

export class DbConnectionBuilder extends __DbConnectionBuilder<
  DbConnection
> {}

export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };
  subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

