// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  npcFid: __t.i64().primaryKey(),
  tokenId: __t.option(__t.string()),
  aiSeed: __t.i64(),
  difficultyTier: __t.i16(),
  budgetFbcWei: __t.string(),
  persona: __t.string(),
  ownerFid: __t.option(__t.i64()),
  managerConfidence: __t.i32(),
  pressureLevel: __t.i32(),
  mood: __t.string(),
  nextDecisionAtMs: __t.i64(),
  lastActiveMs: __t.i64(),
  active: __t.bool(),
});
