// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  role: __t.string(),
  aiSeed: __t.i64(),
  strictness: __t.i32(),
  advantageTendency: __t.i32(),
  offsideTolerance: __t.i32(),
  varPropensity: __t.i32(),
  consistency: __t.i32(),
  fitness: __t.i32(),
  reputation: __t.i32(),
};
