// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.object("PlayerState", {
  playerId: __t.string(),
  ageYears: __t.i16(),
  morale: __t.i32(),
  fatigue: __t.i32(),
  injuryStatus: __t.string(),
  injuryEndMs: __t.option(__t.i64()),
  satisfaction: __t.i32(),
  loyalty: __t.i32(),
  minutesPlayed7D: __t.i32(),
  matchesPlayed7D: __t.i32(),
  matchesBenched7D: __t.i32(),
  lastMatchAtMs: __t.option(__t.i64()),
});


