// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.object("SquadRegistry", {
  squadId: __t.string(),
  sourceFid: __t.i64(),
  followers: __t.i64(),
  intelligenceScore: __t.i32(),
  rank: __t.string(),
  persona: __t.string(),
  tokenId: __t.string(),
  ownerFid: __t.i64(),
  active: __t.bool(),
});


